export * from "./controller.interface";
export * from "./admin.interface";
export * from "./program.interface";
export * from "./contact.interface";
export * from "./user-contact.interface";
export * from "./donation.interface";
export * from "./ngo-profile.interface";
export * from "./blog.interface";
export * from "./gallery.interface";
